name: test

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  setup-keys:
    runs-on: ubuntu-latest
    
    outputs:
      # Forward step outputs to job outputs
      model_keys: ${{ steps.keys.outputs.model_keys }}
      adtype_keys: ${{ steps.keys.outputs.adtype_keys }}

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - uses: julia-actions/cache@v2
        with:
          cache-name: "ad"

      - uses: julia-actions/julia-buildpkg@v1

      # This step sends model_keys and adtype_keys to GITHUB_OUTPUT
      - name: Setup keys
        id: keys
        working-directory: app
        run: ./ad.sh setup

  run-models:
    runs-on: ubuntu-latest
    needs: setup-keys
    strategy:
      matrix:
        model: ${{ fromJSON(needs.setup-keys.outputs.model_keys) }}

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - uses: julia-actions/cache@v2
        with:
          cache-name: "ad"
          include-matrix: false

      - uses: julia-actions/julia-buildpkg@v1

      - name: Run AD
        working-directory: app
        run: ./ad.sh run-model ${{ matrix.model }}
        env:
          ADTYPE_KEYS: ${{ needs.setup-keys.outputs.adtype_keys }}
